################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../CPPUTEST/src/CppUTest/CommandLineArguments.cpp \
../CPPUTEST/src/CppUTest/CommandLineTestRunner.cpp \
../CPPUTEST/src/CppUTest/JUnitTestOutput.cpp \
../CPPUTEST/src/CppUTest/MemoryLeakDetector.cpp \
../CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.cpp \
../CPPUTEST/src/CppUTest/SimpleMutex.cpp \
../CPPUTEST/src/CppUTest/SimpleString.cpp \
../CPPUTEST/src/CppUTest/TeamCityTestOutput.cpp \
../CPPUTEST/src/CppUTest/TestFailure.cpp \
../CPPUTEST/src/CppUTest/TestFilter.cpp \
../CPPUTEST/src/CppUTest/TestHarness_c.cpp \
../CPPUTEST/src/CppUTest/TestMemoryAllocator.cpp \
../CPPUTEST/src/CppUTest/TestOutput.cpp \
../CPPUTEST/src/CppUTest/TestPlugin.cpp \
../CPPUTEST/src/CppUTest/TestRegistry.cpp \
../CPPUTEST/src/CppUTest/TestResult.cpp \
../CPPUTEST/src/CppUTest/TestTestingFixture.cpp \
../CPPUTEST/src/CppUTest/Utest.cpp \
../CPPUTEST/src/CppUTest/UtestPlatform.cpp 

OBJS += \
./CPPUTEST/src/CppUTest/CommandLineArguments.o \
./CPPUTEST/src/CppUTest/CommandLineTestRunner.o \
./CPPUTEST/src/CppUTest/JUnitTestOutput.o \
./CPPUTEST/src/CppUTest/MemoryLeakDetector.o \
./CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.o \
./CPPUTEST/src/CppUTest/SimpleMutex.o \
./CPPUTEST/src/CppUTest/SimpleString.o \
./CPPUTEST/src/CppUTest/TeamCityTestOutput.o \
./CPPUTEST/src/CppUTest/TestFailure.o \
./CPPUTEST/src/CppUTest/TestFilter.o \
./CPPUTEST/src/CppUTest/TestHarness_c.o \
./CPPUTEST/src/CppUTest/TestMemoryAllocator.o \
./CPPUTEST/src/CppUTest/TestOutput.o \
./CPPUTEST/src/CppUTest/TestPlugin.o \
./CPPUTEST/src/CppUTest/TestRegistry.o \
./CPPUTEST/src/CppUTest/TestResult.o \
./CPPUTEST/src/CppUTest/TestTestingFixture.o \
./CPPUTEST/src/CppUTest/Utest.o \
./CPPUTEST/src/CppUTest/UtestPlatform.o 

CPP_DEPS += \
./CPPUTEST/src/CppUTest/CommandLineArguments.d \
./CPPUTEST/src/CppUTest/CommandLineTestRunner.d \
./CPPUTEST/src/CppUTest/JUnitTestOutput.d \
./CPPUTEST/src/CppUTest/MemoryLeakDetector.d \
./CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.d \
./CPPUTEST/src/CppUTest/SimpleMutex.d \
./CPPUTEST/src/CppUTest/SimpleString.d \
./CPPUTEST/src/CppUTest/TeamCityTestOutput.d \
./CPPUTEST/src/CppUTest/TestFailure.d \
./CPPUTEST/src/CppUTest/TestFilter.d \
./CPPUTEST/src/CppUTest/TestHarness_c.d \
./CPPUTEST/src/CppUTest/TestMemoryAllocator.d \
./CPPUTEST/src/CppUTest/TestOutput.d \
./CPPUTEST/src/CppUTest/TestPlugin.d \
./CPPUTEST/src/CppUTest/TestRegistry.d \
./CPPUTEST/src/CppUTest/TestResult.d \
./CPPUTEST/src/CppUTest/TestTestingFixture.d \
./CPPUTEST/src/CppUTest/Utest.d \
./CPPUTEST/src/CppUTest/UtestPlatform.d 


# Each subdirectory must supply rules for building sources it contributes
CPPUTEST/src/CppUTest/CommandLineArguments.o: ../CPPUTEST/src/CppUTest/CommandLineArguments.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/CommandLineArguments.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/CommandLineTestRunner.o: ../CPPUTEST/src/CppUTest/CommandLineTestRunner.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/CommandLineTestRunner.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/JUnitTestOutput.o: ../CPPUTEST/src/CppUTest/JUnitTestOutput.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/JUnitTestOutput.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/MemoryLeakDetector.o: ../CPPUTEST/src/CppUTest/MemoryLeakDetector.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/MemoryLeakDetector.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.o: ../CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/MemoryLeakWarningPlugin.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/SimpleMutex.o: ../CPPUTEST/src/CppUTest/SimpleMutex.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/SimpleMutex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/SimpleString.o: ../CPPUTEST/src/CppUTest/SimpleString.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/SimpleString.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TeamCityTestOutput.o: ../CPPUTEST/src/CppUTest/TeamCityTestOutput.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TeamCityTestOutput.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestFailure.o: ../CPPUTEST/src/CppUTest/TestFailure.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestFailure.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestFilter.o: ../CPPUTEST/src/CppUTest/TestFilter.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestFilter.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestHarness_c.o: ../CPPUTEST/src/CppUTest/TestHarness_c.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestHarness_c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestMemoryAllocator.o: ../CPPUTEST/src/CppUTest/TestMemoryAllocator.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestMemoryAllocator.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestOutput.o: ../CPPUTEST/src/CppUTest/TestOutput.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestOutput.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestPlugin.o: ../CPPUTEST/src/CppUTest/TestPlugin.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestPlugin.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestRegistry.o: ../CPPUTEST/src/CppUTest/TestRegistry.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestRegistry.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestResult.o: ../CPPUTEST/src/CppUTest/TestResult.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestResult.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/TestTestingFixture.o: ../CPPUTEST/src/CppUTest/TestTestingFixture.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/TestTestingFixture.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/Utest.o: ../CPPUTEST/src/CppUTest/Utest.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/Utest.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTest/UtestPlatform.o: ../CPPUTEST/src/CppUTest/UtestPlatform.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTest/UtestPlatform.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

