################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.cpp \
../CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.cpp \
../CPPUTEST/src/CppUTestExt/MemoryReportAllocator.cpp \
../CPPUTEST/src/CppUTestExt/MemoryReportFormatter.cpp \
../CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.cpp \
../CPPUTEST/src/CppUTestExt/MockActualCall.cpp \
../CPPUTEST/src/CppUTestExt/MockExpectedCall.cpp \
../CPPUTEST/src/CppUTestExt/MockExpectedCallsList.cpp \
../CPPUTEST/src/CppUTestExt/MockFailure.cpp \
../CPPUTEST/src/CppUTestExt/MockNamedValue.cpp \
../CPPUTEST/src/CppUTestExt/MockSupport.cpp \
../CPPUTEST/src/CppUTestExt/MockSupportPlugin.cpp \
../CPPUTEST/src/CppUTestExt/MockSupport_c.cpp \
../CPPUTEST/src/CppUTestExt/OrderedTest.cpp 

OBJS += \
./CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.o \
./CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.o \
./CPPUTEST/src/CppUTestExt/MemoryReportAllocator.o \
./CPPUTEST/src/CppUTestExt/MemoryReportFormatter.o \
./CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.o \
./CPPUTEST/src/CppUTestExt/MockActualCall.o \
./CPPUTEST/src/CppUTestExt/MockExpectedCall.o \
./CPPUTEST/src/CppUTestExt/MockExpectedCallsList.o \
./CPPUTEST/src/CppUTestExt/MockFailure.o \
./CPPUTEST/src/CppUTestExt/MockNamedValue.o \
./CPPUTEST/src/CppUTestExt/MockSupport.o \
./CPPUTEST/src/CppUTestExt/MockSupportPlugin.o \
./CPPUTEST/src/CppUTestExt/MockSupport_c.o \
./CPPUTEST/src/CppUTestExt/OrderedTest.o 

CPP_DEPS += \
./CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.d \
./CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.d \
./CPPUTEST/src/CppUTestExt/MemoryReportAllocator.d \
./CPPUTEST/src/CppUTestExt/MemoryReportFormatter.d \
./CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.d \
./CPPUTEST/src/CppUTestExt/MockActualCall.d \
./CPPUTEST/src/CppUTestExt/MockExpectedCall.d \
./CPPUTEST/src/CppUTestExt/MockExpectedCallsList.d \
./CPPUTEST/src/CppUTestExt/MockFailure.d \
./CPPUTEST/src/CppUTestExt/MockNamedValue.d \
./CPPUTEST/src/CppUTestExt/MockSupport.d \
./CPPUTEST/src/CppUTestExt/MockSupportPlugin.d \
./CPPUTEST/src/CppUTestExt/MockSupport_c.d \
./CPPUTEST/src/CppUTestExt/OrderedTest.d 


# Each subdirectory must supply rules for building sources it contributes
CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.o: ../CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/CodeMemoryReportFormatter.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.o: ../CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/IEEE754ExceptionsPlugin.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MemoryReportAllocator.o: ../CPPUTEST/src/CppUTestExt/MemoryReportAllocator.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MemoryReportAllocator.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MemoryReportFormatter.o: ../CPPUTEST/src/CppUTestExt/MemoryReportFormatter.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MemoryReportFormatter.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.o: ../CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MemoryReporterPlugin.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockActualCall.o: ../CPPUTEST/src/CppUTestExt/MockActualCall.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockActualCall.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockExpectedCall.o: ../CPPUTEST/src/CppUTestExt/MockExpectedCall.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockExpectedCall.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockExpectedCallsList.o: ../CPPUTEST/src/CppUTestExt/MockExpectedCallsList.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockExpectedCallsList.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockFailure.o: ../CPPUTEST/src/CppUTestExt/MockFailure.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockFailure.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockNamedValue.o: ../CPPUTEST/src/CppUTestExt/MockNamedValue.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockNamedValue.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockSupport.o: ../CPPUTEST/src/CppUTestExt/MockSupport.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockSupport.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockSupportPlugin.o: ../CPPUTEST/src/CppUTestExt/MockSupportPlugin.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockSupportPlugin.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/MockSupport_c.o: ../CPPUTEST/src/CppUTestExt/MockSupport_c.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/MockSupport_c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CPPUTEST/src/CppUTestExt/OrderedTest.o: ../CPPUTEST/src/CppUTestExt/OrderedTest.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++98 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -DCPPUTEST_STD_CPP_LIB_DISABLED -c -I../USB_HOST/App -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../LWIP/App -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../FATFS/App -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Drivers/CMSIS/Include -I../LWIP/Target -I../FATFS/Target -I../USB_HOST/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/FatFs/src -I../Middlewares/Third_Party/LwIP/src/include/netif -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTest" -I"E:/GitRepo/Com_Module/DevBoard/CPPUTEST/inc/CppUTestExt" -O0 -ffunction-sections -fdata-sections -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"CPPUTEST/src/CppUTestExt/OrderedTest.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

